name: web3mq
description: Provides a modern way of implementing Web3MQ APIs. Web3MQ is the fastest and most scalable social Layer 1 & messaging network.

version: 0.1.0-dev.3
homepage: https://www.web3mq.com

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.1.0
  intl: ^0.18.0
  uuid: ^3.0.7
  collection: ^1.17.0
  web_socket_channel: ^2.0.0
  rxdart: ^0.27.7
  meta: ^1.8.0
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  protobuf: ^2.1.0
  fixnum: ^1.0.1
  cryptography: ^2.0.5
  pointycastle: ^3.6.2
  convert: ^3.1.1
  http: ^0.13.6
  dio: ^5.0.0
  drift: ^1.5.0
  path: ^1.8.0
  path_provider: ^2.0.1
  mutex: ^3.0.0
  graphql: ^5.1.3
  shared_preferences: ^2.1.0
  flutter_sodium: ^0.2.0
  url_launcher: ^6.1.11

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  protoc_plugin: ^20.0.1
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  test_cov_console: ^0.2.2
  drift_dev: ^1.5.2
  flutter_test:
    sdk: flutter
  # test_api: ^0.4.18
