name: web3mq_flutter
repository: https://github.com/Generative-Labs/web3mq_sdk_flutter

packages:
  - packages/*
  - packages/*/example

scripts:
  prepare: melos bootstrap

  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  lint:pub:
    run: |
      melos exec -c 5 --no-private --ignore="*example*" -- \
            flutter pub publish --dry-run
    description: |
      Run `pub publish --dry-run` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: dart format --set-exit-if-changed .
    description: |
      Run `dart format --set-exit-if-changed .` in all packages.

  test:all:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  analyze:all:
    run: melos run analyze && melos run metrics
    description: Run all

  analyze:
    run: |
      melos exec -c 5 --ignore="*example*" -- \
        dart analyze --fatal-infos .
    description: |
      Run `dart analyze` in all packages.
      - Note: you can also rely on your IDEs Dart Analysis / Issues window.
