name: web3mq_core
description: a foundation package for web3mq flutter monorepo.
version: 0.1.0-dev.2
homepage: https://www.web3mq.com

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  json_annotation: ^4.7.0
  convert: ^3.1.1
  equatable: ^2.0.5
  cryptography: ^2.0.5
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
