name: web3mq_core
description: A starting point for Dart libraries or applications.
version: 0.1.0-dev.1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  json_annotation: ^4.7.0
  convert: ^3.1.1
  equatable: ^2.0.5
  cryptography: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
