name: dapp_connect
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  logging: ^1.1.0
  web3mq_core: ^0.1.0-dev.1
  web3mq_websocket: ^0.1.0-dev.1
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  pointycastle: ^3.6.2
  url_launcher: ^6.1.11
  cryptography: ^2.0.5
  rxdart: ^0.27.7
  convert: ^3.1.1
  adaptive_number: ^1.0.0
  shared_preferences: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
