name: web3mq
description: Provides a modern way of implementing Web3MQ APIs. Web3MQ is the fastest and most scalable social Layer 1 & messaging network.

version: 0.2.0-dev.3
homepage: https://www.web3mq.com
repository: https://github.com/Generative-Labs/web3mq_sdk_flutter/tree/main/packages/web3mq_chat
issue_tracker: https://github.com/Generative-Labs/web3mq_sdk_flutter/issues

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  intl: ^0.18.0
  uuid: ^3.0.1
  collection: ^1.17.2
  web_socket_channel: ^2.0.0
  rxdart: ^0.27.7
  meta: ^1.9.1
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  fixnum: ^1.0.1
  cryptography: ^2.0.5
  pointycastle: ^3.6.2
  convert: ^3.1.1
  dio: ^5.0.0
  drift: ^2.12.0
  sqlite3_flutter_libs: ^0.5.15
  path: ^1.8.3
  path_provider: ^2.1.0
  mutex: ^3.0.0
  graphql: ^5.1.3
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.11
  adaptive_number: ^1.0.0
  http_parser: ^4.0.2
  web3mq_websocket: ^0.1.0-dev.2
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  build_runner_core: ^7.2.11
  json_serializable: ^6.0.0
  mocktail: ^1.0.0
  test_cov_console: ^0.2.2
  drift_dev: ^2.12.0
  test_api: ^0.4.18
