#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.4.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::rust2dart::IntoIntoDart;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_initial_user_impl(port_: MessagePort, user_id: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "initial_user",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_user_id = user_id.wire2api();
            move |task_callback| initial_user(api_user_id)
        },
    )
}
fn wire_register_user_impl(port_: MessagePort, user_id: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "register_user",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_user_id = user_id.wire2api();
            move |task_callback| register_user(api_user_id)
        },
    )
}
fn wire_is_mls_group_impl(
    port_: MessagePort,
    user_id: impl Wire2Api<String> + UnwindSafe,
    group_id: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, bool, _>(
        WrapInfo {
            debug_name: "is_mls_group",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_user_id = user_id.wire2api();
            let api_group_id = group_id.wire2api();
            move |task_callback| is_mls_group(api_user_id, api_group_id)
        },
    )
}
fn wire_create_group_impl(
    port_: MessagePort,
    user_id: impl Wire2Api<String> + UnwindSafe,
    group_id: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "create_group",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_user_id = user_id.wire2api();
            let api_group_id = group_id.wire2api();
            move |task_callback| create_group(api_user_id, api_group_id)
        },
    )
}
fn wire_sync_mls_state_impl(
    port_: MessagePort,
    user_id: impl Wire2Api<String> + UnwindSafe,
    group_ids: impl Wire2Api<Vec<String>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "sync_mls_state",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_user_id = user_id.wire2api();
            let api_group_ids = group_ids.wire2api();
            move |task_callback| sync_mls_state(api_user_id, api_group_ids)
        },
    )
}
fn wire_can_add_member_to_group_impl(
    port_: MessagePort,
    user_id: impl Wire2Api<String> + UnwindSafe,
    target_user_id: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, bool, _>(
        WrapInfo {
            debug_name: "can_add_member_to_group",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_user_id = user_id.wire2api();
            let api_target_user_id = target_user_id.wire2api();
            move |task_callback| can_add_member_to_group(api_user_id, api_target_user_id)
        },
    )
}
fn wire_add_member_to_group_impl(
    port_: MessagePort,
    user_id: impl Wire2Api<String> + UnwindSafe,
    member_user_id: impl Wire2Api<String> + UnwindSafe,
    group_id: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "add_member_to_group",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_user_id = user_id.wire2api();
            let api_member_user_id = member_user_id.wire2api();
            let api_group_id = group_id.wire2api();
            move |task_callback| add_member_to_group(api_user_id, api_member_user_id, api_group_id)
        },
    )
}
fn wire_mls_encrypt_msg_impl(
    port_: MessagePort,
    user_id: impl Wire2Api<String> + UnwindSafe,
    msg: impl Wire2Api<String> + UnwindSafe,
    group_id: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "mls_encrypt_msg",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_user_id = user_id.wire2api();
            let api_msg = msg.wire2api();
            let api_group_id = group_id.wire2api();
            move |task_callback| mls_encrypt_msg(api_user_id, api_msg, api_group_id)
        },
    )
}
fn wire_mls_decrypt_msg_impl(
    port_: MessagePort,
    user_id: impl Wire2Api<String> + UnwindSafe,
    msg: impl Wire2Api<String> + UnwindSafe,
    sender_user_id: impl Wire2Api<String> + UnwindSafe,
    group_id: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "mls_decrypt_msg",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_user_id = user_id.wire2api();
            let api_msg = msg.wire2api();
            let api_sender_user_id = sender_user_id.wire2api();
            let api_group_id = group_id.wire2api();
            move |task_callback| {
                mls_decrypt_msg(api_user_id, api_msg, api_sender_user_id, api_group_id)
            }
        },
    )
}
fn wire_handle_mls_group_event_impl(
    port_: MessagePort,
    user_id: impl Wire2Api<String> + UnwindSafe,
    msg_bytes: impl Wire2Api<Vec<u8>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "handle_mls_group_event",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_user_id = user_id.wire2api();
            let api_msg_bytes = msg_bytes.wire2api();
            move |task_callback| handle_mls_group_event(api_user_id, api_msg_bytes)
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
