name: web3mq_http
description: A Web3MQ JSON-RPC client based on the HTTP protocol.
version: 0.1.0-dev.1
homepage: https://www.web3mq.com
repository: https://github.com/Generative-Labs/web3mq_sdk_flutter/tree/main/packages/web3mq_http
issue_tracker: https://github.com/Generative-Labs/web3mq_sdk_flutter/issues

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  path: ^1.8.0
  convert: ^3.1.1
  dio: ^5.0.0
  collection: ^1.17.0
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  cryptography: ^2.0.5
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mocktail: ^0.3.0
  json_serializable: ^6.0.0
  build_runner: ^2.0.0
