name: web3mq_http
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  path: ^1.8.0
  web3mq_core: ^0.1.0
  dio: ^5.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
