name: web3mq_dapp_connect
description: An implementing of `DappConnect`.
version: 0.1.0-dev.1
homepage: https://www.web3mq.com
repository: https://github.com/Generative-Labs/web3mq_sdk_flutter/tree/main/packages/web3mq_dapp_connect
issue_tracker: https://github.com/Generative-Labs/web3mq_sdk_flutter/issues

environment:
  sdk: ">=2.19.4 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  web3mq_core: ^0.1.0-dev.2
  web3mq_websocket: ^0.1.0-dev.2
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  pointycastle: ^3.6.2
  url_launcher: ^6.1.11
  cryptography: ^2.0.5
  rxdart: ^0.27.7
  convert: ^3.1.1
  adaptive_number: ^1.0.0
  shared_preferences: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
