[package]
name = "native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
futures = "0.3"
tokio = { version = "1.14.0", features = ["rt", "macros"] }
anyhow = { version = "1.0.49" }
web3mq_mls_group = { path = "../../../../packages/web3mq_mls_group" }
flutter_rust_bridge = "1"
