name: web3mq_websocket
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://www.web3mq.com

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  web3mq_core: ^0.1.0-dev.1
  uuid: ^3.0.7
  protobuf: ^2.1.0
  web_socket_channel: ^2.0.0
  fixnum: ^1.0.1
  logging: ^1.1.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  cryptography: ^2.0.5
  convert: ^3.1.1
  pointycastle: ^3.6.2
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
