name: web3mq_websocket
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  logging: ^1.1.1
  web_socket_channel: ^2.4.0
  protobuf: ^2.1.0
  fixnum: ^1.1.0
  uuid: ^3.0.7
  web3mq_core: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  protoc_plugin: ^20.0.1
